name: Deploy

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - run: nix develop --command build

      - run: nix run nixpkgs#wrangler -- pages deploy ts/playground/dist --project-name vine-run --branch ${{ github.ref_name }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
